name       : libpagemaker
version    : 0.0.3
release    : 1
source     :
    - http://dev-www.libreoffice.org/src/libpagemaker/libpagemaker-0.0.3.tar.xz : d896dc55dafd84ee3441e0ca497b810809f9eea44805a495c3843412309036d6
license    : MPL-2.0
component  : programming
summary    : Library and tools to use with Adobe PageMaker documents
description: |
    libpagemaker is a library and a set of tools for reading and converting Aldus/Macromedia/Adobe PageMaker documents.
builddeps  :
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
